### ISSUE TITLE
Issue 101

### ISSUE THREAD

**Issue by LamourBt** [damianlajara/RubyAdventure#4]
the error  i am getting `initialize': private method`include' called for WeaponShop:Class (NoMethodError)`

please fix it :(

**Comment by damianlajara** [comment]
What version of ruby are you running?

**Comment by LamourBt** [comment]
does it matter ?  it should run onto every version 💯

**Comment by damianlajara** [comment]
Try using Ruby version 2.2 or greater. I Just tested it with the latest version of ruby, and it runs perfectly fine.

**Comment by LamourBt** [comment]
**`stop being lazy and fix it .......`**

**Comment by LamourBt** [comment]
oh well i will find another game to play :)

**Comment by LamourBt** [comment]
ooohh my gosh, It works ... nice game keep it going

**Comment by damianlajara** [comment]
Glad to hear it! Please let me know if you see any bugs or have any feedback regarding the game itself 👌
